service: my-express-application

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2

functions:
  app:
    handler: app.handler
    events:
      - http: 
          path: /
          method: ANY
      - http: 'ANY {proxy+}'
